### ISSUE TITLE
Check saving/loading functionality for weapons

### ISSUE THREAD

**Issue by sdglitched** [gridhead/gi-loadouts#173]
Check saving/loading functionality for weapons

**Comment by sdglitched** [comment]
Issue with saving/loading of weapons with no Refinement in `GOOD` format

![image](https://github.com/user-attachments/assets/d2d437ea-6d38-41ed-97a2-5cdbd28a5881)

![image](https://github.com/user-attachments/assets/3c8e7192-e043-456b-8a02-14949d3bed27)

**Comment by gridhead** [comment]
Fixed via #171
