### ISSUE TITLE
Limit planned functionality with constellations and profiles

### ISSUE THREAD

**Issue by gridhead** [gridhead/gi-loadouts#236]
As the project could not reach as large an audience as we expected it to reach, we are unfortunately bound to limit the planned functionalities related to character constellations and character profiles. This is to ensure that we remain focused on implementing the core functionalities of the project while steadfastly keeping up with the content updates in Genshin Impact.

While we will be unable to deliver the aforementioned planned functionalities, we promise to remain open to feature requests and bug reports from the community members. We will welcome issue tickets and pull requests fitting with the vision of the project as we hope for growing relevance of the project with future releases of content updates in Genshin Impact going forward.

**Comment by sdglitched** [comment]
We're heartbroken to scale back on these features, but our commitment to the community remains unwavering. :broken_heart:
Regardless, we'll continue delivering core updates, welcome your ideas, and work together to make this project shine. :sparkles:
